# -*- coding: utf-8 -*-
"""DSProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_veEU321EFcN8QfBGv9iwAlkG-9rXkyv
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, StandardScaler
import matplotlib.pyplot as plt
import seaborn as sns

# Load CSV (replace with your path)
data = pd.read_csv(r"/content/sample_data/archive.zip")


print(data.head())
print(data.info())# Inspect the data
print(data.describe())

numeric_cols = ['severity_index','casualties','economic_loss_usd','response_time_hours',
                'aid_amount_usd','response_efficiency_score','recovery_days',
                'latitude','longitude']

for col in numeric_cols:
    data[col] = data[col].fillna(0)

# Drop rows with missing country
data = data.dropna(subset=['country'])

data = data.drop_duplicates()

data['aid_amount_usd'] = data['aid_amount_usd'].astype(float)
data['response_efficiency_score'] = data['response_efficiency_score'].astype(float)

# Aggregate by country
country_data = data.groupby('country').agg({
    'aid_amount_usd':'sum',
    'response_efficiency_score':'mean'  # lower score = more training needed
}).reset_index()

# Optional: invert efficiency score to represent "training needed"
country_data['training_needed'] = 100 - country_data['response_efficiency_score']

most_aid = country_data.loc[country_data['aid_amount_usd'].idxmax()]
print("Country needing most aid:", most_aid['country'], "with aid USD:", most_aid['aid_amount_usd'])

most_training = country_data.loc[country_data['training_needed'].idxmax()]
print("Country needing most training:", most_training['country'], "with training score:", most_training['training_needed'])



country_data.to_csv(r"/content/sample_data/archive (1).zip", index=False)

# Step 10: Verify
print(country_data.head())

# Sort by aid_amount_usd to get top countries
top_aid = country_data.sort_values('aid_amount_usd', ascending=False).head(10)

plt.figure(figsize=(12,6))
plt.plot(top_aid['country'], top_aid['aid_amount_usd'], marker='o', linestyle='-', color='blue')
plt.title('Top 10 Countries with Highest Aid Requirement', fontsize=16)
plt.xlabel('Country', fontsize=12)
plt.ylabel('Total Aid Required (USD)', fontsize=12)
plt.xticks(rotation=45)
plt.grid(True)
plt.tight_layout()
plt.show()

# Sort by training_needed to see top countries (optional)
top_training = country_data.sort_values('training_needed', ascending=False)

# Plot histogram
plt.figure(figsize=(10,6))
plt.hist(top_training['training_needed'], bins=10, color='salmon', edgecolor='black')
plt.title('Distribution of Training Needed Across Countries', fontsize=16)
plt.xlabel('Training Needed (Score)', fontsize=12)
plt.ylabel('Number of Countries', fontsize=12)
plt.grid(axis='y')
plt.tight_layout()
plt.show()

casualties = data.groupby('country')['casualties'].sum().reset_index()

casualties = casualties.sort_values('casualties', ascending=False).head(10)

plt.figure(figsize=(12,6))
plt.bar(casualties['country'], casualties['casualties'], color='orange')
plt.title('Top 10 Countries with Most Casualties', fontsize=16)
plt.xlabel('Country', fontsize=12)
plt.ylabel('Total Casualties', fontsize=12)
plt.xticks(rotation=45)
plt.grid(axis='y')
plt.tight_layout()
plt.show()

country_response = data.groupby('country')['response_time_hours'].mean().reset_index()

# Top 10 countries with least response time
least_response = country_response.sort_values('response_time_hours').head(10)

# Plot pie chart
plt.figure(figsize=(8,8))
plt.pie(least_response['response_time_hours'], labels=least_response['country'],
        autopct='%1.1f%%', startangle=140, colors=plt.cm.Paired.colors)
plt.title('Top 10 Countries with Least Response Time', fontsize=16)
plt.tight_layout()
plt.show()

# Aggregate average recovery days by country
country_recovery = data.groupby('country')['recovery_days'].mean().reset_index()

# Sort descending to see countries with longest recovery first
country_recovery = country_recovery.sort_values('recovery_days', ascending=False)

# Plot bar chart
plt.figure(figsize=(15,6))
plt.bar(country_recovery['country'], country_recovery['recovery_days'], color='teal')
plt.title('Average Recovery Days by Country', fontsize=16)
plt.xlabel('Country', fontsize=12)
plt.ylabel('Average Recovery Days', fontsize=12)
plt.xticks(rotation=90)
plt.grid(axis='y')
plt.tight_layout()
plt.show()